# https://github.com/serverless-components/tencent-express/blob/master/docs/configure.md
# https://cloud.tencent.com/document/product/1154/41775
# https://serverless.cloud.tencent.com/
# https://service-qkxnd3t0-1254232777.gz.apigw.tencentcs.com/test/
component: express
name: apkGo
org: xnng
app: apkGo
stage: dev

inputs:
  src: ./
  functionName: apkGo
  region: ap-guangzhou
  runtime: Nodejs12.16
  exclude:
    - .env
  functionConf:
    timeout: 10
    environment:
      variables:
        NODE_ENV: development
  apigatewayConf:
    enableCORS: true
    protocols:
      - http
      - https
    environment: test