# https://github.com/serverless-components/tencent-express/blob/master/docs/configure.md
# https://cloud.tencent.com/document/product/1154/41775
# https://serverless.cloud.tencent.com/
component: express
name: asd
org: orgDemo
app: appDemo
stage: dev

inputs:
  src: ./
  functionName: asd
  region: ap-guangzhou
  runtime: Nodejs10.15
  exclude:
    - .env
  apigatewayConf:
    enableCORS: true
    protocols:
      - http
      - https
    environment: release