component: express
name: asd
org: orgDemo
app: appDemo
stage: dev

inputs:
  src: ./
  functionName: asd
  region: ap-guangzhou
  runtime: Nodejs10.15
  exclude:
    - .env
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release